### PR TITLE
bringing over pcapng support

### PR DESCRIPTION
**Pull request by BrendanGrant**

### CODE REVIEW

**Comment by BrendanGrant** [comment]
Grrr, did this wrong...

**Comment by odedshimon** [comment]
It's all good :-)

‫בתאריך יום א׳, 29 בנוב׳ 2020 ב-23:34 מאת ‪Brendan Grant‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by BrendanGrant** [comment]
Something to show for the trouble: https://github.com/BrendanGrant/BruteSharkDNS/pull/2

**Comment by odedshimon** [comment]
Very cool! i thought about this feature also :-)
Feel free to Pull Request it when you finished and i will merge it

‫בתאריך יום ב׳, 30 בנוב׳ 2020 ב-1:27 מאת ‪Brendan Grant‬‏ <‪
notifications@github.com‬‏>:‬

**Pull request closed without merging**
